 
version: '3.8'

services:
  apache:
    build: .
    container_name: apache_php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    networks:
      - blog_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8081:80"
    networks:
      - blog_network


networks:
  blog_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
